import { gql } from "@apollo/client";
import Head from "next/head";
import Footer from "../../components/Footer";
import { KometaNav } from "../../components/Navs/KometaNav";
import client from "../../utilities/apollo/apollo-client";
import { KometaHeader } from "../../components/Header/KometaHeader";
import { FeaturedNews } from "../../components/Header/FeaturedNews";
import { CategoryInBrief } from "../../components/News/CategoryInBrief";
import { KometaFooter } from "../../components/Footer/KometaFooter";

const category = {
    id: "111111111111111111111",
    name: "World News",
    description: "What's happening around the world. Be informed and stay in the loop.",
    imageUrl: "https://th.bing.com/th/id/R.00d53a0a4af234e9bea553ca23287e1c?rik=8uXw3DL8JrrLWw&riu=http%3a%2f%2fwww.burmalink.org%2fwp-content%2fuploads%2f2015%2f10%2fKAF-logo.jpg&ehk=6wQ8TfzcSZZFkUid%2b081l8KlwIS7y4P4CdhVgIH42nA%3d&risl=&pid=ImgRaw&r=0&sres=1&sresct=1"
}

const newsBriefs = [
    {
        id: "111111111111111111111",
        title: "World News",
        summary: "What's happening around the world. Be informed and stay in the loop.",
        imageUrl: "https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"
    },
    {
        id: "111111111111111111111",
        title: "World News",
        summary: "What's happening around the world. Be informed and stay in the loop.",
        imageUrl: "https://images.pexels.com/photos/3182750/pexels-photo-3182750.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"
    },
    {
        id: "111111111111111111111",
        title: "World News",
        summary: "What's happening around the world. Be informed and stay in the loop.",
        imageUrl: "https://images.pexels.com/photos/3182746/pexels-photo-3182746.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"
    },
    {
        id: "111111111111111111111",
        title: "World News",
        summary: "What's happening around the world. Be informed and stay in the loop.",
        imageUrl: "https://images.pexels.com/photos/3184296/pexels-photo-3184296.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"
    },
    {
        id: "111111111111111111111",
        title: "World News",
        summary: "What's happening around the world. Be informed and stay in the loop.",
        imageUrl: "https://images.pexels.com/photos/3184311/pexels-photo-3184311.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500"
    },
    {
        id: "111111111111111111111",
        title: "World News",
        summary: "What's happening around the world. Be informed and stay in the loop.",
        imageUrl: "https://images.pexels.com/photos/3184338/pexels-photo-3184338.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"
    }
]

export async function getServerSideProps() {
  const { data } = await client.query({
    query: gql`
      query AllArticles {
        articles {
          id
          publishedAt
          author {
            username
            email
          }
          blocks {
            type
            blockId
            sequenceNo
            tableData {
              rows {
                items
              }
            }
            paragraphData {
              text
            }
            imageData {
              url
              filename
              caption
            }
            listData {
              items {
                text
                sequenceNo
              }
            }
            headerData {
              text
              level
            }
          }
        }
      }
    `,
  });

  return {
    props: {
      articles: data.articles.slice(0, 20),
    },
  };
}

export default function Home({ articles }) {
  return (
    <div className="">
      <Head>
        <title>ကီၢ်လါတၢ်ဘိးဘၣ်ရၤလီၤ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <KometaNav />
        <FeaturedNews articles={articles} />
        <CategoryInBrief category={ category } articleBriefs={ newsBriefs } />
        <CategoryInBrief category={ category } articleBriefs={ newsBriefs } />
        <CategoryInBrief category={ category } articleBriefs={ newsBriefs } />
      </main>
      <KometaFooter />
    </div>
  );
}
